language: go
sudo: required

go:
- 1.x

env:
  global:
  - FILE_NAME: aidosd_${TRAVIS_TAG}_linux_amd64
  
before_install:
- go get -u github.com/axw/gocov/gocov
- go get -u github.com/alecthomas/gometalinter
- go get -u github.com/mattn/goveralls
- go get -u golang.org/x/tools/cmd/cover
- export PATH=$PATH:$GOPATH/bin
- gometalinter --install --update
- go generate -x ./...
script:
- travis_wait 30 go test ./... -v  -timeout 100m
after_success:
- gometalinter -e bindata --deadline=1000s ./...
- go build -o adkd -ldflags "-X github.com/AidosKuneen/aidosd/Version=\"${TRAVIS_TAG}\""
- tar -cvf  ${FILE_NAME}.tar adkd aidosd.conf
- gzip ${FILE_NAME}.tar
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
   secure: rkEPGDjOiHklUO96HWw0sCNvln/7tOt0Qwc998t2zjcI3AwTpIwtLaC/VRz63v718yX5cH3TgmbqWGsuew4PYSsLK+j4ixCpyzZDYTZKDGZ63BQO/T+4hwr/fWnljicnEIyBRRigv7fd4DlNojnEOqH0/CpUg/kcejAXQRuGssrgi+Dc1EcUhA1KJMXbMnuYUFZwuwyUOIwyFpFdfm+QXsX7mAAfuevl6H6Ia2qRlpAiUID7sEcFIpA0ZNoxc300SNsINjmmbh6VwbmoxH/J6JwPYqa6PTTIJKuwhXzxDhUdoGbNQ0WM+dFph/DxJBUeuMWtuG5rDMbZcuIe9h3mS8+mwIG1zraYPokJf6E3ZjeZx+EBp2BshhvfNVg1n+xLa4OcCqpzhQy2a+tVqv3rC+z4/LjEDCWhy6+rZJ8c8sH9dC2sBwkRZN4ob1kFRzYZ7Ypl6tNYWFwMVJiX52jlmSJgi8cvAkDE8A2w2ohlid8kGso6m2ME282TlnIiCeA5ka8VI7x9HywmIl4RrP2N2Hq+20lGrEe8Ue6+3A+2iLpOZGa4k8Ipi6xbB6cqQg8YNCp+2FsjCfjHcEpXDO6qeFwO0e8wL/TqT2au16QC4PG43RHl5KBu4ScQetMZ+jwQcyB8nPOlqvEnQ5ZODhgBCYOAc1LoPXeikt9AIyU+AwM=
  file:  ${FILE_NAME}.tar.gz
  on:
    tags: true
    all_branches: true
condition: "$TRAVIS_TAG =~ ^v[0-9].*$"
